- Integrated a patch from Chris Ross:   * have siproxd compile on Solaris and BSD/OS (more to come)   * ./configure option --with-libosip-prefix   * properly handle getopt_long()/getopt() - First attempt of iptables support. Routines to add/remove   DNAT entries must still be done.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -18,6 +18,7 @@ dnl      5-Sep-2003     tries   test for pthreads before libosip stuff
 dnl     19-Sep-2003     tries   DMALLOC support
 dnl	 1-Nov-2003	tries	check for NETFILTER (IPTABLES)
 dnl	18-Nov-2003	tries	include sysconfdir to search for config
+dnl	19-Nov-2003	tries	changes to support Solaris & BSD/OS
 dnl
 dnl
 dnl
@@ -52,6 +53,7 @@ dnl Checks for needed programs.
 dnl
 AC_PROG_AWK
 AC_PROG_CC
+AC_PROG_CPP
 AC_PROG_INSTALL
 AC_PROG_LN_S
 
@@ -95,34 +97,46 @@ dnl    --enable-dmalloc
 dnl
 dnl system specific stuff
 dnl
-AC_MSG_CHECKING("target platform")
+AC_MSG_CHECKING(target platform)
 case "$target" in
   *-*-linux*)
-    AC_MSG_RESULT("Linux")
+    AC_MSG_RESULT(Linux)
     AC_DEFINE(_LINUX,,[building on Linux platform])
     AC_CHECK_HEADERS(linux/ip_masq.h)
     AC_CHECK_HEADERS(linux/netfilter.h)
     ;;
   *-*-freebsd*)
-    AC_MSG_RESULT("FreeBSD")
+    AC_MSG_RESULT(FreeBSD)
     AC_DEFINE(_BSD,,[building on BSD platform])
     AC_DEFINE(_FREEBSD,,[building on FreeBSD platform])
     CPPFLAGS="$CPPFLAGS -I/usr/local/include/"
     LIBS="$LIBS -L/usr/local/lib/ -lgnugetopt"
     ;;
   *-*-openbsd*)
-    AC_MSG_RESULT("OpenBSD")
+    AC_MSG_RESULT(OpenBSD)
     AC_DEFINE(_BSD,,[building on BSD platform])
     AC_DEFINE(_OPENBSD,,[building on OpenBSD platform])
     CPPFLAGS="$CPPFLAGS -I/usr/local/include/"
     LIBS="$LIBS -L/usr/local/lib/"
     ;;
   *-*-netbsd*)
-    AC_MSG_RESULT("NetBSD")
+    AC_MSG_RESULT(NetBSD)
     AC_DEFINE(_BSD,,[building on BSD platform])
     AC_DEFINE(_NETBSD,,[building on NetBSD platform])
     CPPFLAGS="$CPPFLAGS -I/usr/pkg/include"
     LIBS="$LIBS -L/usr/pkg/lib"
+    ;;
+  *-*-bsdi* | *-*-bsdos*)
+    AC_MSG_RESULT(BSD/OS)
+    AC_DEFINE(_BSD,,[building on BSD platform])
+    AC_DEFINE(_BSDOS,,[building on BSD/OS platform])
+    ;;
+  *-*-solaris2*)
+    # It's easier to do this here, rather than AC_CHECK_LIBS for all of the
+    # things that are/might be in libsocket or libnsl...
+    AC_MSG_RESULT(Solaris 2.x)
+    AC_DEFINE(_SOLARIS,,[building on Solaris platform])
+    LIBS="$LIBS -lsocket -lnsl"
     ;;
   *)
     ;;
@@ -134,9 +148,9 @@ dnl Feature:
 dnl  Fli4l uClibc support (only available on Linux, yet)
 dnl
 build_fli4l_uclibc="no"
+AC_MSG_CHECKING(whether build for FLI4L uClibc)
 case "$target" in
   *-*-linux*)
-   AC_MSG_CHECKING("build for FLI4L uClibc")
    AC_ARG_ENABLE(fli4l-uclibc,
       [  --enable-fli4l-uclibc       FLI4L: build for uClibc],
       build_fli4l_uclibc=$enableval,)
@@ -144,18 +158,18 @@ case "$target" in
    ;;
 
   *)
-    AC_MSG_RESULT("FEATURE fli4l-uclibc not available on this platform")
+    AC_MSG_RESULT(fli4l-uclibc not available on this platform)
     ;;
 esac
 
 dnl
 dnl Feature:
-dnl    Flifl libc5 support (only available on Linux, yet)
+dnl    Fli4l libc5 support (only available on Linux, yet)
 dnl
 build_fli4l_libc5="no"
+AC_MSG_CHECKING(building for FLI4L libc5)
 case "$target" in
   *-*-linux*)
-   AC_MSG_CHECKING("building for FLI4L libc5")
    AC_ARG_ENABLE(fli4l-libc5,
       [  --enable-fli4l-libc5        FLI4L: build for libc5],
       build_fli4l_libc5=$enableval,)
@@ -163,7 +177,7 @@ case "$target" in
    ;;
 
   *)
-    AC_MSG_RESULT("FEATURE fli4l-libc5 not available on this platform")
+    AC_MSG_RESULT(fli4l-libc5 not available on this platform)
     ;;
 esac
 
@@ -210,16 +224,32 @@ fi
 
 
 dnl
+dnl add
+dnl    --with-libosip-prefix=DIR
+dnl
+libosip_prefix_dir=""
+AC_ARG_WITH(libosip-prefix,
+   [  --with-libosip-prefix=DIR   use libosip2 from DIR/include and DIR/lib],
+   if test x$withval != x ; then libosip_prefix_dir="$withval"; fi,
+   )
+AC_SUBST(libosip_prefix_dir)
+
+dnl
 dnl Check for libosip
 dnl
+if test x$libosip_prefix_dir != x; then
+   LIBS="-L$libosip_prefix_dir/lib $LIBS"
+   CPPFLAGS="$CPPFLAGS -I$libosip_prefix_dir/include"
+fi
+
 if test "x$build_static_libosip" = "xno"; then
    dnl link dynamically (default)
    AC_CHECK_LIB(osip2, osip_init,,
-      echo "*** ERROR: libosip2 is required!";exit 1;,
+      echo "*** ERROR: libosip2 is required!  "\
+            "Maybe you need to use --with-libosip-prefix ?"; exit 1;,
       [-losipparser2])
    AC_CHECK_LIB(osipparser2, parser_init,,
-      echo "*** ERROR: libosipparser2 is required!";exit 1;,
-      [-losip2])
+      echo "*** ERROR: libosipparser2 is required!";exit 1;,)
 else
    dnl link statically to this lib
    dnl (this probably only will work on linux yet...)
@@ -250,7 +280,7 @@ dnl
 AC_HEADER_STDC
 AC_CHECK_HEADERS(sys/time.h unistd.h errno.h)
 AC_CHECK_HEADERS(stdarg.h varargs.h)
-AC_CHECK_HEADERS(pwd.h)
+AC_CHECK_HEADERS(pwd.h getopt.h)
 
 dnl
 dnl Checks for typedefs, structures, and compiler characteristics.
@@ -261,10 +291,10 @@ AC_HEADER_TIME
 AC_STRUCT_TM
 
 dnl check for typedef socklen (not available on SUSE 5.3 for example)
-AC_MSG_CHECKING("typedef socklen_t")
+AC_MSG_CHECKING(typedef socklen_t)
 AC_EGREP_HEADER([typedef.*socklen_t], sys/socket.h,
-    AC_MSG_RESULT("available"),
-    AC_MSG_RESULT("not available - create DEFINE to uint")
+    AC_MSG_RESULT(available),
+    AC_MSG_RESULT(not available - create DEFINE to uint)
     AC_DEFINE(socklen_t, [unsigned int],[typedef socklen_t available])
 )
 
@@ -280,6 +310,7 @@ AC_CHECK_FUNCS(getuid setuid getgid setgid getpwnam chroot)
 AC_CHECK_FUNCS(socket bind select read send sendto)
 AC_CHECK_FUNCS(strncpy strchr strstr sprintf vfprintf vsnprintf)
 AC_CHECK_FUNCS(fgets sscanf hstrerror)
+AC_CHECK_FUNCS(inet_pton inet_ntop inet_aton inet_ntoa)
 
 
 dnl
