made build under SUSE 5.3 (Flifl) and optionally link statically against libosip and pthreds

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -5,6 +5,8 @@ dnl	before time		a lot happend before start of history
 dnl	 8-Sep-2002	tries	included more tests for used functions
 dnl	17-Sep-2002	tries	fail configure if needed libs not there
 dnl	14-Nov-2002	tries	support for *BSD systems
+dnl	22-Mar-2003	tries	check for sockaddr_t, hstrerror()
+dnl				feature almost-static (for Fli4l use)
 dnl
 dnl
 dnl
@@ -70,7 +72,6 @@ for each in $extra_libs; do
 done
 
 
-
 dnl
 dnl system specific stuff
 dnl
@@ -106,10 +107,45 @@ case "$target" in
 esac
 
 dnl
+dnl Features:
+dnl    almost-static	(only available on Linux, yet)
+dnl
+case "$target" in
+  *-*-linux*)
+   AC_MSG_CHECKING("build almost static")
+   AC_ARG_ENABLE(almost-static,
+      [  --enable-almost-static       only link dynamically to libc, rest static],
+      build_almost_static=$enableval,
+      build_almost_static="no")
+   AC_MSG_RESULT($build_almost_static)
+   ;;
+
+  *)
+    AC_MSG_RESULT("FEATURE almost-static not available on this platform")
+    ;;
+esac
+
+
+dnl
 dnl Check for libosip
 dnl
-AC_CHECK_LIB(osip, parser_init,,
-   echo "*** ERROR: libosip is required!";exit 1;)
+if test "x$build_almost_static" = "xno"; then
+   dnl link dynamically (default)
+   AC_CHECK_LIB(osip, parser_init,,
+      echo "*** ERROR: libosip is required!";exit 1;)
+else
+   dnl link statically to this lib
+   dnl (this probably only will work on linux yet...)
+   AC_MSG_CHECKING("where I can find libosip.a")
+   libosip_static=`find /lib /usr/lib /usr/local/lib $extra_libs \
+                   -name libosip.a 2>/dev/null|head -1`
+   if test "x$libosip_static" != "x"; then
+      LIBS="$libosip_static $LIBS"
+      AC_MSG_RESULT($libosip_static)
+   else
+      echo "*** ERROR: a static libosip library is required!";exit 1;
+   fi
+fi
 
 
 dnl
@@ -117,9 +153,26 @@ dnl Check for pthreads
 dnl
 ACX_PTHREAD(,
    echo "*** ERROR: pthreads is required!"; exit 1;)
-LIBS="$PTHREAD_LIBS $LIBS"
-CFLAGS="$CFLAGS $PTHREAD_CFLAGS"
-CC="$PTHREAD_CC"
+if test "x$build_almost_static" = "xno"; then
+   dnl link dynamically (default)
+   LIBS="$PTHREAD_LIBS $LIBS"
+   CFLAGS="$CFLAGS $PTHREAD_CFLAGS"
+   CC="$PTHREAD_CC"
+else
+   dnl link statically to this lib
+   dnl (this probably only will work on linux yet...)
+   AC_MSG_CHECKING("where I can find static threads library")
+   libpthreads_static=`find /lib /usr/lib /usr/local/lib $extra_libs \
+                       -name 'lib*thread*.a' 2>/dev/null| \
+                       egrep 'lib[p]?thread[s]?.a' |head -1`
+   if test "x$libpthreads_static" != "x"; then
+      LIBS="$libpthreads_static $LIBS"
+      AC_MSG_RESULT($libpthreads_static)
+   else
+      echo "*** ERROR: a static threads library is required!";exit 1;
+   fi
+   CC="$PTHREAD_CC"
+fi
 
 
 dnl
@@ -138,6 +191,14 @@ AC_TYPE_SIZE_T
 AC_HEADER_TIME
 AC_STRUCT_TM
 
+dnl check for typedef socklen (not available on SUSE 5.3 for example)
+AC_MSG_CHECKING("typedef socklen_t")
+AC_EGREP_HEADER([typedef.*socklen_t], sys/socket.h,
+    AC_MSG_RESULT("available"),
+    AC_MSG_RESULT("not available - create DEFINE to uint")
+    AC_DEFINE(socklen_t, [unsigned int],[typedef socklen_t available])
+)
+
 dnl
 dnl Checks for library functions.
 dnl
@@ -149,7 +210,7 @@ AC_CHECK_FUNCS(getopt_long daemon syslog)
 AC_CHECK_FUNCS(getuid setuid getgid setgid getpwnam chroot)
 AC_CHECK_FUNCS(socket bind select read send sendto)
 AC_CHECK_FUNCS(strncpy strchr strstr sprintf vfprintf vsnprintf)
-AC_CHECK_FUNCS(fgets sscanf)
+AC_CHECK_FUNCS(fgets sscanf hstrerror)
 
 
 AC_SUBST(CPPFLAGS)
