rel 3.3.4

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -11,7 +11,8 @@ dnl				--enable-uclibc (uClibc building support)
 dnl	29-Mar-2003	tries	added support for libosip2
 dnl	 6-Apr-2003	tries	redone the fli4l specific build options
 dnl				now: --enable-fli4l-libc5, --enable-fli4l-uclibc
-dnl	 7-Apr-2003	tries	added siproxd.spex to autoconf process
+dnl	 7-Apr-2003	tries	added siproxd.spec to autoconf process
+dnl	31-Jul-2003	tries	changed to support OSIP2 only
 dnl
 dnl
 dnl
@@ -27,7 +28,7 @@ dnl Release Version
 dnl
 SPD_MAJOR_VERSION=0
 SPD_MINOR_VERSION=3
-SPD_MICRO_VERSION=3
+SPD_MICRO_VERSION=4
 
 SPD_VERSION=$SPD_MAJOR_VERSION.$SPD_MINOR_VERSION.$SPD_MICRO_VERSION
 
@@ -168,32 +169,29 @@ fi
 dnl
 dnl Check for libosip
 dnl
-osiplib=osip
-have_osip2=no
-AC_MSG_CHECKING("force to use libosip1")
-AC_ARG_ENABLE(force-osip1,
-   [  --enable-force-osip1        force the use of libosip1],
-   AC_MSG_RESULT("yes"),
-   AC_MSG_RESULT("no")
-   dnl do we have libosip2 available?
-   AC_CHECK_LIB(osip2, main, 
-      [osiplib=osip2 have_osip2=yes], )
-   )
-AC_DEFINE_UNQUOTED(LIBOSIPVER, ["$osiplib"], [type of libosip])
-if test "x$have_osip2" = "xyes"; then
-   AC_DEFINE(HAVE_OSIP2, , [have osip2 installed])
-fi
-
 if test "x$build_static_libosip" = "xno"; then
    dnl link dynamically (default)
-   AC_CHECK_LIB($osiplib, parser_init,,
-      echo "*** ERROR: libosip is required!";exit 1;)
+   AC_CHECK_LIB(osip2, osip_init,,
+      echo "*** ERROR: libosip2 is required!";exit 1;,
+      [-losipparser2])
+   AC_CHECK_LIB(osipparser2, parser_init,,
+      echo "*** ERROR: libosipparser2 is required!";exit 1;,
+      [-losip2])
 else
    dnl link statically to this lib
    dnl (this probably only will work on linux yet...)
-   AC_MSG_CHECKING("where I can find lib$osiplib.a")
+   AC_MSG_CHECKING("where I can find libosip2.a")
    libosip_static=`find $extra_libs /lib /usr/lib /usr/local/lib \
-                   -name lib$osiplib.a 2>/dev/null|head -1`
+                   -name libosip2.a 2>/dev/null|head -1`
+   if test "x$libosip_static" != "x"; then
+      LIBS="$libosip_static $LIBS"
+      AC_MSG_RESULT($libosip_static)
+   else
+      echo "*** ERROR: a static libosip library is required!";exit 1;
+   fi
+   AC_MSG_CHECKING("where I can find libosipparser2.a")
+   libosip_static=`find $extra_libs /lib /usr/lib /usr/local/lib \
+                   -name libosipparser2.a 2>/dev/null|head -1`
    if test "x$libosip_static" != "x"; then
       LIBS="$libosip_static $LIBS"
       AC_MSG_RESULT($libosip_static)
